### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by relance-haklar** [recursivetree/seat-alliance-industry#10] opened 2023-01-05 03:38 UTC
After updating to 1.1.8, whenever someone tries to supply an order they receive an error 500.

**Comment by recursivetree** [comment] 2023-01-05 09:27
This does not happen for me. Can you send me what you order and the laravel logs of the error? 

Here is the documentation of how to find the error log: https://eveseat.github.io/docs/troubleshooting/#checking-log-files

**Comment by kaylak4520** [comment] 2023-01-05 17:27
Hi @recursivetree, 

I'm Mikayla. I work with @relance-haklar on our SeAT instance. We have many orders, which I will screenshot the list for you. (All have the same issue). When accessing any order and adding resources (IE Biomass: Quantity 1 and clicking add), we get a 500 internal server error.
![Screenshot 2023-01-05 at 12 59 09 PM](https://user-images.githubusercontent.com/8121659/210837942-18bbd2f2-f0b9-47e2-b991-2ddecd1c269c.png) (This is the orders list)


[https:rxsk.seat.tempestcoalition.com:allianceindustry:order:331:deliveries:add.pdf](https://github.com/recursivetree/seat-alliance-industry/files/10354102/https.rxsk.seat.tempestcoalition.com.allianceindustry.order.331.deliveries.add.pdf) (This is the app debug output after clicking "add" since installing 1.1.8)



[laravel-2023-01-05.log](https://github.com/recursivetree/seat-alliance-industry/files/10354279/laravel-2023-01-05.log)
Here is the log you asked for.   Only showed in Web, not Worker docker.

**Comment by recursivetree** [comment] 2023-01-05 17:45
Thanks for the logs, I'll take a look at it. It is completely normal that it only shows in the web container, because web handles all web related things(like handling a request). The worker container is mostly there to load data from the ESI.

**Comment by recursivetree** [comment] 2023-01-05 17:46
On another note, did you ever install seat-inventory? The crash is related to seat-alliance-industry thinking seat-inventory is installed too, but then not actually finding it.

**Comment by recursivetree** [comment] 2023-01-05 17:50
I found the issue. I'll release a fix shortly. In the meantime, you can install seat-inventory and the crash should go away.

**Comment by kaylak4520** [comment] 2023-01-05 17:53
> 

THANK YOU SO MUCH!

I'll look into Seat-Inventory as well!

**Comment by recursivetree** [comment] 2023-01-05 17:55
It should be fixed in the lastest release 1.1.9

**Closed as completed by recursivetree** 2023-01-05 17:55 UTC

**Comment by kaylak4520** [comment] 2023-01-05 18:07
@recursivetree I've confirmed that also installing recursivetree/seat-inventory fixes the issue.  Thanks a bunch!

**Comment by recursivetree** [comment] 2023-01-05 18:09
If you install plugins, you normally also update all other plugins, meaning you would have got the fix anyways. 

Sorry for the inconvenience of this bug. But if people report bugs, it means the plugin is used, which is nice to hear.
